//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medvedeva_PrivateAdertisementService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ads
    {
        public int AdID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> AdTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ImagePath { get; set; }
    
        public virtual AdTypes AdTypes { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
